version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: wildhunt-repo-nginx
    volumes:
      - "./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
  nexus:
    image: sonatype/nexus3
    container_name: wildhunt-repo-nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
volumes:
  nexus-data: {}