version: "3.9"
services:
  nexus:
    image: sonatype/nexus3
    container_name: wildhunt-repo-nexus
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
  nginx:
    image: nginx:latest
    container_name: wildhunt-repo-nginx
    restart: always
    ports:
      - "81:80"
    volumes:
      - "/docker/nginx/conf.d/default.conf: /etc/nginx/conf.d/default.conf"
    depends_on:
      - nexus
volumes:
  nexus-data: {}